from .Arena import Arena as Arena
from .Box import Box as Box
from .Snake import Snake as Snake
from .Mamam import Mamam as Mamam
from .DBController import DBController as DBController
from .Authentication import Authentication as Authentication
from .Login import Login as Login
from .Register import Register as Register
from .Leaderboard import Leaderboard as Leaderboard
from .MainMenu import MainMenu as MainMenu
